---
title: "부동산 데이터 대시보드"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll

---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(dplyr)
library(stringr)
library(knitr)
library(kableExtra)

today <- format(Sys.time(), "%Y.%m.%d.")
```

### 뉴스
```{r}

  URL <- "https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=101&sid2=260"
  res <- read_html(URL)

  pattern <- ".newsflash_body a"
  title <- res %>% 
    html_nodes(pattern) %>% 
    html_text() %>% 
    str_trim()
  title.select <- title[title!="" & title!="동영상기사"]
  
  pattern <- ".newsflash_body a"
  link <- res %>% 
    html_nodes(pattern) %>% 
    html_attr("href")
  link.select <- unique(link)
  
  tab <- cbind(today, title.select, link.select) %>% as_tibble()

  df <- tab %>% select(today, title.select)

  names(df) <- c("Date", "Title")

  df %>% head(15) %>%
    kable(format="html", escape=FALSE) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```




### 관심지역 실거래
```{r}
data <- read.csv("/Users/jameslee/Documents/SKKU/1학년 1학기/경제데이터분석입문/Data/QAE2023 test/국토교통부 실거래 광진구 5월.csv")
knitr::kable(head(data))
```


